# Build the test projects
steps:
- name: 'mcr.microsoft.com/dotnet/core/sdk:2.1'
  entrypoint: 'bash'
  #args: ['bash', '-c', 'chmod 777 aimaps/aimaps_cli/linux-x64/Gsqa.Tools.AiMaps.Console.dll && chmod 777 aimaps/aimaps_cli/linux-x64/Selenium/chromedriver && dotnet aimaps/aimaps_cli/linux-x64/Gsqa.Tools.AiMaps.Console.dll src=maps/nuevaeps/NuevaEPS.aiml']
  args:
  - '-c'
  - |
    chmod 777 aimaps/aimaps_cli/linux-x64/* \
    && chmod 777 aimaps/aimaps_cli/linux-x64/Selenium/chromedriver \
    && chmod 777 maps/nuevaeps/* \
    && apt update -y \
    && apt upgrade -y \
    && apt install wget -y \
    && wget 'https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_94.0.4606.81-1_amd64.deb' \
    && apt install ./google-chrome-stable_94.0.4606.81-1_amd64.deb -y \
    && google-chrome --version \
    && dotnet aimaps/aimaps_cli/linux-x64/Gsqa.Tools.AiMaps.Console.dll src=maps/nuevaeps/google.aiml \
    && cd maps/nuevaeps/.tmp/ \
    && ls
    
