# Build the test projects
steps:
- name: 'mcr.microsoft.com/dotnet/sdk:3.1'
  entrypoint: 'bash'
  #args: ['bash', '-c', 'chmod 777 aimaps/aimaps_cli/linux-x64/Gsqa.Tools.AiMaps.Console.dll && chmod 777 aimaps/aimaps_cli/linux-x64/Selenium/chromedriver && dotnet aimaps/aimaps_cli/linux-x64/Gsqa.Tools.AiMaps.Console.dll src=maps/nuevaeps/NuevaEPS.aiml']
  args:
  - '-c'
  - |
    chmod 777 aimaps/aimaps_cli/linux-x64/Gsqa.Tools.AiMaps.Console.dll \
    && chmod 777 aimaps/aimaps_cli/linux-x64/Selenium/chromedriver \
    && apt update -y \
    && apt upgrade -y \
    && apt install wget -y \
    && wget 'https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb' \
    && apt install ./google-chrome-stable_current_amd64.deb -y \
    && google-chrome --version \
    && dotnet aimaps/aimaps_cli/linux-x64/Gsqa.Tools.AiMaps.Console.dll src=maps/nuevaeps/google.aiml
    
