# Build the test projects
steps:
- name: 'mcr.microsoft.com/windows:20H2'
  entrypoint: 'pws'
  #args: ['bash', '-c', 'chmod 777 aimaps/aimaps_cli/linux-x64/Gsqa.Tools.AiMaps.Console.dll && chmod 777 aimaps/aimaps_cli/linux-x64/Selenium/chromedriver && dotnet aimaps/aimaps_cli/linux-x64/Gsqa.Tools.AiMaps.Console.dll src=maps/nuevaeps/NuevaEPS.aiml']
  args: [ls]
  #- '-c'
  #- |
    #ls
    #chmod 777 aimaps/aimaps_cli/linux-x64/Gsqa.Tools.AiMaps.Console.dll \
    #&& chmod 777 aimaps/aimaps_cli/linux-x64/Selenium/chromedriver \
    #&& cat /etc/os-release
    #&& dotnet aimaps/aimaps_cli/linux-x64/Gsqa.Tools.AiMaps.Console.dll src=maps/nuevaeps/NuevaEPS.aiml
    
