# Cloud builder for the dotnet builder.

steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=gcr.io/$PROJECT_ID/dotnet'
  - '.'

# Build the test projects
- name: 'gcr.io/$PROJECT_ID/dotnet'
  args: ['build']
  dir: 'aimaps/aimaps_cli/linux-x64/Gsqa.Tools.AiMaps.Console.dll'

images:
- 'gcr.io/$PROJECT_ID/dotnet'
