# RUPET Pipeline
# The TIA - Team!

trigger:
- '*'

schedules:
  - cron: "0 * * * *"
    displayName: Schedule job
    branches:
      include:
      - f-6443
      - main
    always: true

pool:
  vmImage: $(agentImage)

jobs:
- job: LoadAgentNode1
  displayName: nequi-functional
  continueOnError: true
  workspace:
    clean: outputs
  steps:
    - template: nequi-functional.yml